# Switches
set_property PACKAGE_PIN V17 	 [get_ports {C}]					
set_property IOSTANDARD LVCMOS33 [get_ports {C}]
set_property PACKAGE_PIN V16 	 [get_ports {B}]					
set_property IOSTANDARD LVCMOS33 [get_ports {B}]
set_property PACKAGE_PIN W16 	 [get_ports {A}]					
set_property IOSTANDARD LVCMOS33 [get_ports {A}]

# LEDs
set_property PACKAGE_PIN U16 	 [get_ports {F0}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F0}]
set_property PACKAGE_PIN E19 	 [get_ports {F1}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F1}]
set_property PACKAGE_PIN U19 	 [get_ports {F2}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F2}]
set_property PACKAGE_PIN V19 	 [get_ports {F3}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F3}]
set_property PACKAGE_PIN W18 	 [get_ports {F4}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F4}]
set_property PACKAGE_PIN U15 	 [get_ports {F5}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F5}]
set_property PACKAGE_PIN U14 	 [get_ports {F6}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F6}]
set_property PACKAGE_PIN V14 	 [get_ports {F7}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F7}]