# Switches
set_property PACKAGE_PIN V17 	 [get_ports {ABC[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {ABC[0]}]
set_property PACKAGE_PIN V16 	 [get_ports {ABC[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {ABC[1]}]
set_property PACKAGE_PIN W16 	 [get_ports {ABC[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {ABC[2]}]

# LEDs
set_property PACKAGE_PIN U16 	 [get_ports {F[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F[0]}]
set_property PACKAGE_PIN E19 	 [get_ports {F[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F[1]}]
set_property PACKAGE_PIN U19 	 [get_ports {F[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F[2]}]
set_property PACKAGE_PIN V19 	 [get_ports {F[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F[3]}]
set_property PACKAGE_PIN W18 	 [get_ports {F[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F[4]}]
set_property PACKAGE_PIN U15 	 [get_ports {F[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F[5]}]
set_property PACKAGE_PIN U14 	 [get_ports {F[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F[6]}]
set_property PACKAGE_PIN V14 	 [get_ports {F[7]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {F[7]}]