# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.runs/synth_1/oled_arcade_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a15tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.cache/wt [current_project]
set_property parent.project_path C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/david/AppData/Roaming/Xilinx/Vivado/2025.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:cmod_a7-15t:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/audio_engine.sv
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/breakout_game.sv
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/button_debounce_active_low.sv
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/edge_pulse.sv
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/i2c_3byte_tx_master.sv
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/invaders_game.sv
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/menu_controller.sv
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/pong_game.sv
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/snake_game.sv
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/ssd1306_arcade_driver.sv
  C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/sources_1/new/oled_arcade_top.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/constrs_1/new/oled_arcade_xdc.xdc
set_property used_in_implementation false [get_files C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/constrs_1/new/oled_arcade_xdc.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/david/FPGA_Vivado_Designs/CMOD_Arcade_Instructable/CMOD_Arcade_Instructable.srcs/utils_1/imports/synth_1/oled_arcade_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top oled_arcade_top -part xc7a15tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef oled_arcade_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file oled_arcade_top_utilization_synth.rpt -pb oled_arcade_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
